name: Pre Merge Checks

on:
  pull_request:
    paths:
      - 'proj1/**'
      - 'proj2/**'
      - 'proj3/**'
      - 'eventservice/**'
      - '.github/workflows/pre-merge.yaml'

permissions:
    contents: read
    pull-requests: write

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - project: proj1
            jdk: 24
          - project: proj2
            jdk: 24
          - project: proj3
            jdk: 24
          - project: eventservice
            jdk: 22
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '${{ matrix.jdk }}'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven of ${{ matrix.project }}
        if: ${{ matrix.project != '' }}
        working-directory: ${{ matrix.project }}
        run: mvn --batch-mode --update-snapshots verify
